export const advancedSearchEndPoints = {
    semesters: 'lookups/semesters',
    colleges: 'lookups/colleges',
    departments: 'lookups/departments',
    degrees: 'lookups/degrees',
    majors: 'lookups/majors',
    minors: 'lookups/minors',
    programs: 'lookups/programs',
    concentrations: 'lookups/concentrations',
    advisors: 'lookups/advisors',
    instructors: 'lookups/instructors',
    coaches: 'lookups/coaches',
    courseData: 'lookups/course-data',
    academicStanding: 'lookups/academic-standing',
    gender: 'lookups/gender',
    race: 'lookups/race',
    cohort: 'lookups/cohort',
    studentType: 'lookups/student-type',
    grades: 'lookups/grades',
    terms: 'lookups/terms',
    systemActivity: 'lookups/system-activity',
    testScore: 'lookups/test-score',
    levels: 'lookups/levels'
};
